version: '2'
services:
  db:
    image: mysql:latest
    container_name: todo-mysql
    ports:
      - "33306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: abekoh
      MYSQL_PASSWORD: hokeba
    restart: always
  backend:
    image: openjdk:11
    container_name: todo-backend
    volumes:
      - "./jar:/app"
    working_dir:
    ports:
      - "9000:8080"
    command: >
      java -jar webflux-todo.jar
      --spring.profiles.active=compose
    links:
      - db
    restart: always
  frontend:
    image: node:12.14.0
    container_name: todo-frontend
    ports:
      - "9001:3000"
    volumes:
      - "./workspace-front:/app"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    working_dir: /app
    command: >
      bash -c
      "npm install && npmrun build:compose && npm run start:compose"
    links:
      - backend
    restart: always
